### ISSUE TITLE
[GSoC] Find enhancements

### ISSUE THREAD

**Issue by scholtzan** [google/xi-mac#174]
This is a basic roadmap of the steps I am planning to take to provide a more advanced interface for find and replace in xi mac. These steps are related to https://github.com/google/xi-editor/issues/634

## Roadmap

_I am planning to refine this roadmap over time._

- [x] Interface for search, replace and Regex search
- [x] Fixing of bugs
    - [x] Find UI magnifier icon not shown (https://github.com/google/xi-mac/issues/120)
    - [x] Prevent xi mac from becoming unresponsive while search interface is open
- [x] Highlighting of matched strings in xi mac
- [x] Integrate search using multiple queries (https://github.com/google/xi-mac/pull/229)
- [ ] Colorizing of results based on groupings when using regular expressions
- [x] Colorizing of results when using multiple search queries (https://github.com/google/xi-mac/pull/229)

Updating documentation and tests is part of each of these steps.
Other issues related to this: https://github.com/google/xi-mac/issues/9, https://github.com/google/xi-mac/issues/154
