### ISSUE TITLE
[GSoC] Xi-Mac UI Improvements

### ISSUE THREAD

**Issue by nangtrongvuon** [google/xi-mac#176]
This is a list of goals that I aim to meet in order to improve Xi-Mac's UI and make it more featured and usable editor on MacOS.

This roadmap is a work in progress and subject to changes and improvements.

**Roadmap**
- [x] Status bar
- [x] Implement UI elements for LSP Support
    - [x] Autocomplete Menu
    - [x] Show Definition Menu
    - [x] Go to Definition Menu
- [ ] Implement split views
- [x] Tab/Window behavior examination
